services:
  react:
    container_name: licencjat_test
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_test
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
