version: '3.8'

services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins_test
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins_home:
